### ISSUE TITLE
新群

### ISSUE THREAD

**Issue by mousezz** [acmerindex/acmerindex.github.io#3]
ACMer～清纯读书群 215672931     耗子  小分支，可以分享自己喜欢的书，偶尔闲聊一下关于看书之类的事 。书籍不限定领域，方向，语言，但必须是出版书籍或者硕士、博士论文。比较优秀的全年龄网络小说也可以。

**Comment by cubercsl** [comment]
下次提交可以自己在 [`data/groups.yaml`](https://github.com/acmerindex/acmerindex.github.io/blob/main/data/groups.yaml) 中添加相关数据发起 PR。
